version: '3.8'

services:
  django:
    container_name: my_to_do_list
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    restart: always
    networks:
      - mynetwork
    volumes:
      - django_data:/app

  celery:
    build:
      context: .
    container_name: celery
    command: celery -A todo worker -l info
    volumes:
      - ./app:/app
    depends_on:
      - redis
    networks:
      - mynetwork

  redis:
    image: "redis:latest"
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - mynetwork

  postgres:
    container_name: postgres
    image: postgres:13
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qweopkl
      POSTGRES_INITDB_ARGS: "-A md5"
    ports:
      - "5432:5432"
    restart: always
    networks:
      - mynetwork
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  django_data:
  postgres_data:

networks:
  mynetwork:
